#!/usr/bin/env bash
set -e

# Extract ABI from a Foundry project and save as TypeScript
#
# Usage: ./extract-foundry-abi.sh <foundry-project-path> <ContractName> [output-name]
#
# Examples:
#   ./extract-foundry-abi.sh /path/to/project MyContract my-contract

if [ $# -lt 2 ]; then
  echo "Usage: $0 <foundry-project-path> <ContractName> [output-name]"
  echo ""
  echo "Arguments:"
  echo "  foundry-project-path  Path to the Foundry project root"
  echo "  ContractName          Name of the contract/interface to extract"
  echo "  output-name           Optional: output filename (without .ts extension)"
  echo "                        Defaults to lowercase ContractName"
  echo ""
  echo "Examples:"
  echo "  $0 ../seaport Seaport"
  exit 1
fi

PROJECT_PATH="$1"
CONTRACT_NAME="$2"
OUTPUT_NAME="${3:-$(echo "$CONTRACT_NAME" | sed 's/\([A-Z]\)/-\1/g' | sed 's/^-//' | tr '[:upper:]' '[:lower:]')}"

ABI_DIR="$(dirname "$0")/abi"
OUTPUT_FILE="$ABI_DIR/$OUTPUT_NAME.ts"

# Validate project path
if [ ! -d "$PROJECT_PATH" ]; then
  echo "Error: Project path '$PROJECT_PATH' does not exist"
  exit 1
fi

# Check for foundry.toml
if [ ! -f "$PROJECT_PATH/foundry.toml" ]; then
  echo "Error: No foundry.toml found in '$PROJECT_PATH'"
  echo "       Make sure this is a Foundry project"
  exit 1
fi

echo "Extracting ABI for $CONTRACT_NAME from $PROJECT_PATH..."

# Build first to ensure artifacts exist
echo "  Building project..."
(cd "$PROJECT_PATH" && forge build --silent) || {
  echo "  Warning: forge build failed, trying to extract anyway..."
}

# Extract ABI as JSON
echo "  Extracting ABI..."
ABI_JSON=$(cd "$PROJECT_PATH" && forge inspect "$CONTRACT_NAME" abi --json 2>/dev/null) || {
  echo "Error: Failed to extract ABI for '$CONTRACT_NAME'"
  echo "       Make sure the contract name is correct"
  echo ""
  echo "Available contracts:"
  (cd "$PROJECT_PATH" && forge inspect --list 2>/dev/null | head -20) || true
  exit 1
}

# Convert contract name to SCREAMING_SNAKE_CASE for the export
EXPORT_NAME=$(echo "$CONTRACT_NAME" | sed 's/\([a-z]\)\([A-Z]\)/\1_\2/g' | tr '[:lower:]' '[:upper:]')_ABI

# Create TypeScript file
{
  echo "// Source: $PROJECT_PATH ($CONTRACT_NAME)"
  echo "// Generated by extract-foundry-abi.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo ""
  echo "export const $EXPORT_NAME = $ABI_JSON as const;"
} >"$OUTPUT_FILE"

echo "  Saved to $OUTPUT_FILE"
echo ""
echo "Done! Export name: $EXPORT_NAME"
